'use strict';

const NeuralNetwork  = require('../brain/NeuralNetwork');
const WorkingMemory  = require('./WorkingMemory');
const ReplayBuffer   = require('./ReplayBuffer');
const { ARITY, VOCAB_SIZE } = require('./tokens');

/**
 * DecompositionController — the prefrontal-cortex-inspired module that learns
 * *which* sub-expression to reduce next at each step of problem-solving.
 *
 * ── Neuroscience analogues ────────────────────────────────────────────────
 *
 *  PFC (prefrontal cortex)
 *    The neural network inside the controller embodies the "executive"
 *    decision-making function of the PFC: given the current state of working
 *    memory it outputs preference scores for each possible reduction position.
 *
 *  Basal ganglia gating
 *    selectAction() implements action gating: it first enumerates *valid*
 *    candidate reductions (via WorkingMemory.validReductions), then uses the
 *    controller network to rank them and selects the best — or, with
 *    probability explorationRate, selects randomly (exploration).
 *
 *  Hippocampal replay (see ReplayBuffer)
 *    storeTrace() / replayTrain() implement an offline consolidation loop
 *    that does not perturb the specialist BrainRegions.
 *
 * ── Architecture ─────────────────────────────────────────────────────────
 *
 *  Input layer  : maxSlots × VOCAB_SIZE one-hot working-memory encoding
 *  Hidden layers: two layers of `hiddenSize` neurons (tanh)
 *  Output layer : maxSlots scores (sigmoid), one per possible start position
 *
 *  During action selection only scores at *valid* reduction positions are
 *  considered; invalid positions are masked out.  This keeps the action
 *  space grounded in the current memory state.
 *
 * ── Training modes ───────────────────────────────────────────────────────
 *
 *  1. Imitation (supervised warm-start)
 *     trainImitation() accepts (stateVec, targetStart) pairs generated by
 *     the expert leftmost-reduction policy.  The one-hot target trains the
 *     network to score the expert's choice highest.
 *
 *  2. Replay consolidation
 *     replayTrain() samples successful episode traces from the ReplayBuffer
 *     and extracts (stateVec, chosenStart) pairs for further supervised
 *     fine-tuning — without touching the specialist BrainRegions.
 */
class DecompositionController {
  /**
   * @param {object} [config]
   * @param {number} [config.maxSlots=16]         Working memory slots
   * @param {number} [config.hiddenSize=64]        Neurons per hidden layer
   * @param {number} [config.learningRate=0.05]    Initial LR for the policy NN
   * @param {number} [config.explorationRate=0.15] ε for ε-greedy action selection
   * @param {number} [config.replayCapacity=2000]  Max stored episodes
   */
  constructor(config = {}) {
    this.config = {
      maxSlots:        16,
      hiddenSize:      64,
      learningRate:    0.05,
      explorationRate: 0.15,
      replayCapacity:  2000,
      ...config,
    };

    const inputSize  = this.config.maxSlots * VOCAB_SIZE;
    const outputSize = this.config.maxSlots;

    this.network = new NeuralNetwork({
      architecture:     [inputSize, this.config.hiddenSize, this.config.hiddenSize, outputSize],
      learningRate:     this.config.learningRate,
      hiddenActivation: 'tanh',
      outputActivation: 'sigmoid',
    });

    this.replayBuffer = new ReplayBuffer(this.config.replayCapacity);
    this.trained      = false;
    this.trainCount   = 0;
  }

  // ── Action selection (basal-ganglia gating) ───────────────────────────────

  /**
   * Select which reduction to apply given the current working memory.
   *
   * The selection policy:
   *  • With probability `explorationRate` (or when `forceExplore` is true),
   *    pick a uniformly random valid reduction (exploration).
   *  • Otherwise, score all valid reductions using the policy network and
   *    return the one with the highest score (exploitation).
   *
   * Returns null when no valid reduction is currently possible (the caller
   * should treat this as an "unsolvable state" signal).
   *
   * @param {WorkingMemory} mem
   * @param {boolean}       [forceExplore=false]
   * @returns {{ start: number, op: number, args: number[] } | null}
   */
  selectAction(mem, forceExplore = false) {
    const candidates = mem.validReductions();
    if (candidates.length === 0) return null;

    if (forceExplore || Math.random() < this.config.explorationRate) {
      return candidates[Math.floor(Math.random() * candidates.length)];
    }

    const stateVec = mem.toVector();
    const scores   = this.network.predict(stateVec);

    let best      = candidates[0];
    let bestScore = scores[best.start];

    for (let i = 1; i < candidates.length; i++) {
      const score = scores[candidates[i].start];
      if (score > bestScore) {
        bestScore = score;
        best      = candidates[i];
      }
    }
    return best;
  }

  // ── Training ──────────────────────────────────────────────────────────────

  /**
   * Imitation learning: train the policy network from expert-labelled
   * (state, action) pairs.
   *
   * Each example specifies the working-memory state vector and the start
   * position the expert chose.  The network learns to output ~1 at the target
   * position and ~0 elsewhere (one-hot regression via MSE).
   *
   * This is the "warm-start" phase: supervised imitation bootstraps the
   * controller before any exploration is needed.
   *
   * @param {Array<{ stateVec: number[], targetStart: number }>} examples
   * @param {number} [epochs=20]
   */
  trainImitation(examples, epochs = 20) {
    if (examples.length === 0) return;

    const outputSize = this.config.maxSlots;
    const samples    = examples.map(({ stateVec, targetStart }) => {
      const target = new Array(outputSize).fill(0);
      if (targetStart >= 0 && targetStart < outputSize) {
        target[targetStart] = 1;
      }
      return { input: stateVec, output: target };
    });

    this.network.train(samples, epochs);
    this.trainCount++;
    this.trained = true;
  }

  /**
   * Replay consolidation: sample successful episode traces from the replay
   * buffer and extract (stateVec, chosenStart) pairs for fine-tuning.
   *
   * Only *solved* episodes are used so the controller reinforces strategies
   * that actually work.
   *
   * @param {number} [batchSize=32]
   * @param {number} [epochs=5]
   */
  replayTrain(batchSize = 32, epochs = 5) {
    const traces = this.replayBuffer.samplePositive(batchSize);
    if (traces.length === 0) return;

    const examples = [];
    for (const trace of traces) {
      for (const step of (trace.steps || [])) {
        if (step.stateVec && step.chosenStart !== undefined) {
          examples.push({ stateVec: step.stateVec, targetStart: step.chosenStart });
        }
      }
    }
    this.trainImitation(examples, epochs);
  }

  // ── Replay buffer management ──────────────────────────────────────────────

  /**
   * Store a completed episode trace in the replay buffer.
   * @param {{ steps: Array, reward: number, solved: boolean }} trace
   */
  storeTrace(trace) {
    this.replayBuffer.push(trace);
  }

  // ── Introspection / serialisation ─────────────────────────────────────────

  /** Plain-object summary for use in Brain.introspect(). */
  getInfo() {
    return {
      trained:         this.trained,
      trainCount:      this.trainCount,
      explorationRate: this.config.explorationRate,
      architecture:    [...this.network.architecture],
      replayBuffer:    this.replayBuffer.getStats(),
    };
  }

  toJSON() {
    return {
      config:      this.config,
      trained:     this.trained,
      trainCount:  this.trainCount,
      network:     this.network.toJSON(),
      replayStats: this.replayBuffer.getStats(),
    };
  }

  static fromJSON(data) {
    const ctrl       = new DecompositionController(data.config || {});
    ctrl.trained     = data.trained    || false;
    ctrl.trainCount  = data.trainCount || 0;
    if (data.network) {
      ctrl.network = NeuralNetwork.fromJSON(data.network);
    }
    return ctrl;
  }
}

module.exports = DecompositionController;
