'use strict';

const NeuralNetwork    = require('../brain/NeuralNetwork');
const WorkingMemory    = require('./WorkingMemory');
const ReplayBuffer     = require('./ReplayBuffer');
const EmbeddingTable   = require('./EmbeddingTable');
const GatingNetwork    = require('./GatingNetwork');
const { ARITY, VOCAB_SIZE, TOKEN } = require('./tokens');

/**
 * DecompositionController — the prefrontal-cortex-inspired module that learns
 * *which* sub-expression to reduce next at each step of problem-solving.
 *
 * ── Neuroscience analogues ────────────────────────────────────────────────
 *
 *  PFC (prefrontal cortex)
 *    The neural network inside the controller embodies the "executive"
 *    decision-making function of the PFC: given the current state of working
 *    memory it outputs preference scores for each possible reduction position.
 *
 *  Basal ganglia gating
 *    selectAction() implements action gating: it first enumerates *valid*
 *    candidate reductions (via WorkingMemory.validReductions or the learned
 *    GatingNetwork), then uses the controller network to rank them and selects
 *    the best — or, with probability explorationRate, selects randomly.
 *
 *  Hippocampal replay (see ReplayBuffer)
 *    storeTrace() / replayTrain() implement an offline consolidation loop
 *    that does not perturb the specialist BrainRegions.
 *
 * ── Architecture ─────────────────────────────────────────────────────────
 *
 *  One-hot mode (default, embeddingDim = null):
 *    Input layer  : maxSlots × VOCAB_SIZE one-hot working-memory encoding
 *    Hidden layers: two layers of `hiddenSize` neurons (tanh)
 *    Output layer : maxSlots scores (sigmoid), one per possible start position
 *
 *  Embedding mode (embeddingDim set):
 *    An EmbeddingTable (Phase 1) maps each token ID to a dense vector of size
 *    `embeddingDim`.  The policy network input becomes maxSlots × embeddingDim.
 *    Embedding weights are updated jointly with the policy network via
 *    backpropagation during trainImitation().
 *
 *  Gating mode (useGating = true, requires embedding mode):
 *    A GatingNetwork (Phase 2) predicts which slot positions are valid
 *    reduction starts purely from embeddings, replacing the hard-coded ARITY
 *    table as the candidate filter in selectAction().
 *
 * ── Training modes ───────────────────────────────────────────────────────
 *
 *  1. Imitation (supervised warm-start)
 *     trainImitation() accepts (stateVec, targetStart) pairs generated by
 *     the expert leftmost-reduction policy.  The one-hot target trains the
 *     network to score the expert's choice highest.
 *     When embedding mode is active, the raw slot tokens (rawSlots) are used
 *     to compute input gradients that also update the EmbeddingTable.
 *
 *  2. Replay consolidation
 *     replayTrain() samples successful episode traces from the ReplayBuffer
 *     and extracts (stateVec, chosenStart) pairs for further supervised
 *     fine-tuning — without touching the specialist BrainRegions.
 */
class DecompositionController {
  /**
   * @param {object}  [config]
   * @param {number}  [config.maxSlots=16]         Working memory slots
   * @param {number}  [config.hiddenSize=64]        Neurons per hidden layer
   * @param {number}  [config.learningRate=0.05]    Initial LR for the policy NN
   * @param {number}  [config.explorationRate=0.15] ε for ε-greedy action selection
   * @param {number}  [config.replayCapacity=2000]  Max stored episodes
   * @param {number|null} [config.embeddingDim=null]
   *   When set, enables Phase-1 embedding mode.  The policy network input
   *   size becomes maxSlots × embeddingDim and an EmbeddingTable is created.
   * @param {boolean} [config.useGating=false]
   *   When true (requires embeddingDim), enables Phase-2 gating mode.
   */
  constructor(config = {}) {
    this.config = {
      maxSlots:        16,
      hiddenSize:      64,
      learningRate:    0.05,
      explorationRate: 0.15,
      replayCapacity:  2000,
      embeddingDim:    null,   // null = one-hot mode; number = embedding mode
      useGating:       false,  // Phase 2 gating network
      ...config,
    };

    const { maxSlots, hiddenSize, learningRate, embeddingDim, useGating } = this.config;

    // ── Phase 1: EmbeddingTable ──────────────────────────────────────────────
    this.embeddingTable = embeddingDim
      ? new EmbeddingTable({ vocabSize: VOCAB_SIZE, dim: embeddingDim, learningRate })
      : null;

    const valueDim   = 1;
    const inputSize  = embeddingDim
      ? maxSlots * (embeddingDim + valueDim)
      : maxSlots * (VOCAB_SIZE + valueDim);
    const outputSize = maxSlots;

    this.network = new NeuralNetwork({
      architecture:     [inputSize, hiddenSize, hiddenSize, outputSize],
      learningRate,
      hiddenActivation: 'tanh',
      outputActivation: 'sigmoid',
    });

    // ── Phase 2: GatingNetwork ───────────────────────────────────────────────
    this.gatingNetwork = (useGating && embeddingDim)
      ? new GatingNetwork({ embeddingDim, learningRate })
      : null;

    this.replayBuffer = new ReplayBuffer(this.config.replayCapacity);
    this.trained      = false;
    this.trainCount   = 0;
  }

  // ── Action selection (basal-ganglia gating) ───────────────────────────────

  /**
   * Select which reduction to apply given the current working memory.
   *
   * Candidate enumeration (in priority order):
   *  1. Phase 2 — GatingNetwork (when active):
   *       Scores all slot positions using the learned gating network.
   *       Positions above the threshold are the candidate set.
   *       Falls back to validReductions() when the gating set is empty.
   *  2. Fallback — ARITY-based symbolic filter (always available):
   *       Uses WorkingMemory.validReductions() for a hard-coded correct set.
   *
   * Policy:
   *  • With probability `explorationRate` (or `forceExplore`), pick randomly.
   *  • Otherwise, score all candidates with the policy network and pick the best.
   *
   * Returns null when no valid reduction is currently possible.
   *
   * @param {WorkingMemory} mem
   * @param {boolean}       [forceExplore=false]
   * @returns {{ start: number, op: number, args: number[] } | null}
   */
  selectAction(mem, forceExplore = false) {
    // ── Phase 2: gating-based candidate enumeration ──────────────────────────
    let candidates;
    if (this.gatingNetwork && this.embeddingTable) {
      const predictedStarts = this.gatingNetwork.predictValidStarts(
        mem.slots, mem.length, this.embeddingTable
      );
      // Filter to positions that are also structurally reducible (safety net)
      const structural = mem.validReductions();
      candidates = structural.filter(c => predictedStarts.includes(c.start));
      // Fallback: if gating predicts nothing, use full structural set
      if (candidates.length === 0) candidates = structural;
    } else {
      candidates = mem.validReductions();
    }

    if (candidates.length === 0) return null;

    if (forceExplore || Math.random() < this.config.explorationRate) {
      return candidates[Math.floor(Math.random() * candidates.length)];
    }

    // ── Policy network scoring ───────────────────────────────────────────────
    const stateVec = mem.toVector(this.embeddingTable);
    const scores   = this.network.predict(stateVec);

    let best      = candidates[0];
    let bestScore = scores[best.start];

    for (let i = 1; i < candidates.length; i++) {
      const score = scores[candidates[i].start];
      if (score > bestScore) {
        bestScore = score;
        best      = candidates[i];
      }
    }
    return best;
  }

  // ── Training ──────────────────────────────────────────────────────────────

  /**
   * Imitation learning: train the policy network from expert-labelled
   * (state, action) pairs.
   *
   * One-hot mode (no embeddingTable):
   *   Uses the pre-computed `stateVec` from each example.  Delegates to
   *   NeuralNetwork.train() for efficiency.
   *
   * Embedding mode (embeddingTable present):
   *   Uses `rawSlots` to compute the embedded input dynamically.  Runs a
   *   custom per-sample training loop via backwardWithInputGrad() so that
   *   gradient is propagated back into the EmbeddingTable alongside the policy
   *   network weights (joint training, Phase 1).
   *
   * Gating mode (gatingNetwork present):
   *   Builds gating examples from `rawSlots` and `validStarts` (Phase 2) and
   *   trains the GatingNetwork concurrently.
   *
   * @param {Array<{
   *   stateVec?:    number[],
    *   rawSlots?:    number[],
    *   rawValues?:   number[],
   *   validStarts?: number[],
   *   targetStart:  number
   * }>} examples
   * @param {number} [epochs=20]
   */
  trainImitation(examples, epochs = 20) {
    if (examples.length === 0) return;

    const outputSize = this.config.maxSlots;

    // ── Phase 2: train gating network ────────────────────────────────────────
    if (this.gatingNetwork && this.embeddingTable) {
      const gatingExamples = [];
      for (const ex of examples) {
        if (!ex.rawSlots || !ex.validStarts) continue;
        for (let s = 0; s < this.config.maxSlots; s++) {
          const tok = ex.rawSlots[s];
          const emb = this.embeddingTable.lookup(tok);
          gatingExamples.push({
            embedding: emb,
            valid:     ex.validStarts.includes(s) ? 1 : 0,
          });
        }
      }
      if (gatingExamples.length > 0) {
        this.gatingNetwork.train(gatingExamples, epochs);
      }
    }

    // ── Phase 1: embedding mode with joint gradient update ───────────────────
    if (this.embeddingTable) {
      const embExamples = examples.map(ex => {
        const target = new Array(outputSize).fill(0);
        if (ex.targetStart >= 0 && ex.targetStart < outputSize) {
          target[ex.targetStart] = 1;
        }
        return { rawSlots: ex.rawSlots, rawValues: ex.rawValues, stateVec: ex.stateVec, target };
      });

      for (let epoch = 0; epoch < epochs; epoch++) {
        // Shuffle
        for (let i = embExamples.length - 1; i > 0; i--) {
          const j = Math.floor(Math.random() * (i + 1));
          [embExamples[i], embExamples[j]] = [embExamples[j], embExamples[i]];
        }

        for (const ex of embExamples) {
          // Build embedded input from raw slots when available, else stateVec
          let input;
          if (ex.rawSlots) {
            // Temporary WorkingMemory to use toVector(table)
            const tmpMem  = new WorkingMemory(this.config.maxSlots);
            tmpMem.slots  = ex.rawSlots;
            if (ex.rawValues) tmpMem.values = ex.rawValues;
            input = tmpMem.toVector(this.embeddingTable);
          } else {
            input = ex.stateVec;
          }

          const { inputGrad } = this.network.backwardWithInputGrad(input, ex.target);

          // Propagate gradient into embedding table (per slot)
          if (ex.rawSlots) {
            const dim = this.embeddingTable.dim;
            const slotSize = dim + 1;
            for (let s = 0; s < this.config.maxSlots; s++) {
              const tok      = ex.rawSlots[s];
              const start    = s * slotSize;
              const gradSlice = inputGrad.slice(start, start + dim);
              this.embeddingTable.update(tok, gradSlice);
            }
          }
        }
      }

      this.trainCount++;
      this.trained = true;
      return;
    }

    // ── Default: one-hot mode ────────────────────────────────────────────────
    const samples = examples.map(({ stateVec, targetStart }) => {
      const target = new Array(outputSize).fill(0);
      if (targetStart >= 0 && targetStart < outputSize) {
        target[targetStart] = 1;
      }
      return { input: stateVec, output: target };
    });

    this.network.train(samples, epochs);
    this.trainCount++;
    this.trained = true;
  }

  /**
   * Replay consolidation: sample successful episode traces from the replay
   * buffer and extract (stateVec, chosenStart) pairs for fine-tuning.
   *
   * Only *solved* episodes are used so the controller reinforces strategies
   * that actually work.
   *
   * @param {number} [batchSize=32]
   * @param {number} [epochs=5]
   */
  replayTrain(batchSize = 32, epochs = 5) {
    const traces = this.replayBuffer.samplePositive(batchSize);
    if (traces.length === 0) return;

    const examples = [];
    for (const trace of traces) {
      for (const step of (trace.steps || [])) {
        if (step.stateVec && step.chosenStart !== undefined) {
          examples.push({ stateVec: step.stateVec, targetStart: step.chosenStart });
        }
      }
    }
    this.trainImitation(examples, epochs);
  }

  // ── Replay buffer management ──────────────────────────────────────────────

  /**
   * Store a completed episode trace in the replay buffer.
   * @param {{ steps: Array, reward: number, solved: boolean }} trace
   */
  storeTrace(trace) {
    this.replayBuffer.push(trace);
  }

  // ── Introspection / serialisation ─────────────────────────────────────────

  /** Plain-object summary for use in Brain.introspect(). */
  getInfo() {
    return {
      trained:         this.trained,
      trainCount:      this.trainCount,
      explorationRate: this.config.explorationRate,
      architecture:    [...this.network.architecture],
      embeddingDim:    this.config.embeddingDim || null,
      useGating:       this.config.useGating || false,
      replayBuffer:    this.replayBuffer.getStats(),
    };
  }

  toJSON() {
    return {
      config:         this.config,
      trained:        this.trained,
      trainCount:     this.trainCount,
      network:        this.network.toJSON(),
      replayStats:    this.replayBuffer.getStats(),
      embeddingTable: this.embeddingTable ? this.embeddingTable.toJSON() : null,
      gatingNetwork:  this.gatingNetwork  ? this.gatingNetwork.toJSON()  : null,
    };
  }

  static fromJSON(data) {
    const ctrl       = new DecompositionController(data.config || {});
    ctrl.trained     = data.trained    || false;
    ctrl.trainCount  = data.trainCount || 0;
    if (data.network) {
      ctrl.network = NeuralNetwork.fromJSON(data.network);
    }
    if (data.embeddingTable) {
      ctrl.embeddingTable = EmbeddingTable.fromJSON(data.embeddingTable);
    }
    if (data.gatingNetwork) {
      ctrl.gatingNetwork = GatingNetwork.fromJSON(data.gatingNetwork);
    }
    return ctrl;
  }
}

module.exports = DecompositionController;
